### ISSUE TITLE
Any links on offisial site do not work

### ISSUE THREAD

**Issue by valVk** [kraken-php/framework#2]
Any links on offisial site do not work. Documentation dos not available.

**Comment by khelle** [comment]
Right now, we are in the process of creating documentation and finishing official website. If you want to be notified about progress, please follow us on https://twitter.com/kraken_php :)

**Comment by khelle** [comment]
I started working on publicly available documentation for Kraken project in separate project https://github.com/kraken-php/docs . It will be published on website when each topic is completed.

**Comment by khelle** [comment]
Documentation has been placed in official website, which is now finished.
