### ISSUE TITLE
Error starting server with kraken.server

### ISSUE THREAD

**Issue by riky-cloud** [kraken-php/framework#44]
hi,
i have a ready project kraken with composer 
"composer create-project --prefer-dist kraken-php/kraken"
but when starting server "kraken.server" i get error "kraken.server: command not found"

how to fix it?

**Comment by khelle** [comment]
It seems you don't have configured your environment to automatically detec PHP scripts. in this case you need to prepend all scripts with a path to you PHP binary, which means both `kraken` and `kraken.server` scripts should be called as `php kraken` and `php kraken.server`.

**Comment by riky-cloud** [comment]
oh thanks it work,
but sorry, i get new error with 
server
Server is booting...
PHP Warning:  Uncaught  Throwable trace:
     0. [WarningError] "require(): data:/ wrapper is disabled in the server configuration by allow_url_include=0" in /ConfigFactory.php:48
    Stack trace:
     0. [throwable] Kraken\Throwable\Error\WarningError(...) in ErrorHandler:63
     1. [call] Kraken\Throwable\ErrorHandler::handleError(2, ""require(): data:// wrapper is d...", "/opt/lampp/htdocs/kraken/test/kr...", 48, Array) in ConfigFactory:48
     2. [call] Undefinedrequire() in ConfigFactory:48
     3. [call] Kraken\Config\ConfigFactory->Kraken\Config{closure}() in unknown:0
     4. [call] Undefinedcall_user_func_array(Closure, Array) in SimpleFactoryTrait:128
     5. [call] Kraken\Util\Factory\SimpleFactory->create() in ConfigProvider:180
     6. [call] Kraken\Root\Provider\ConfigProvider->createConfig("/opt/lampp/htdocs/kraken/test/kr...") in ConfigProvider:239
     7. [call] Kraken\Root\Provider\ConfigProvider->configure(Kraken\Config\Config) in ConfigProvider:103
     8. [call] Kraken\Root\Provider\ConfigProvider->register(Kraken\Root\Console\Server in /opt/lampp/htdocs/kraken/test/kraken/vendor/kraken-php/throwable/ErrorHandler.php on line 63
PHP Fatal error:  Kraken\Config\ConfigFactory::Kraken\Config{closure}(): Failed opening required 'data://text/plain;base64,PD9waHAKCi8qKgogKiAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICogRGVmYXVsdCBjb25maWd1cmF0aW9uIGZvciBDb25zb2xlIFNlcnZlci4KICoKICogRm9yIG1vcmUgaW5mb3JtYXRpb24gdmlzaXQ6IGh0dHA6Ly9rcmFrZW4tcGhwLmNvbS9kb2NzCiAqIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogKi8KcmV0dXJuIFsKICAgIC8qKgogICAgICogLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICAgICAqIEFkZGl0aW9uYWwgY29uZmlndXJhdGlvbiBmaWxlIHRvIGxvYWQuCiAgICAgKiAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgICogVGhpcyB2YXJpYWJsZS in /opt/lampp/htdocs/kraken/test/kraken/vendor/kraken-php/config/ConfigFactory.php on line 48
    Throwable trace:
     0. [FatalError] "Kraken\Config\ConfigFactory::Kraken\Config{closure}(): Failed opening required 'data:/plain;base64,PD9waHAKCi8qKgogKiAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICogRGVmYXVsdCBjb25maWd1cmF0aW9uIGZvciBDb25zb2xlIFNlcnZlci4KICoKICogRm9yIG1vcmUgaW5mb3JtYXRpb24gdmlzaXQ6IGh0dHA6Ly9rcmFrZW4tcGhwLmNvbS9kb2NzCiAqIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogKi8KcmV0dXJuIFsKICAgIC8qKgogICAgICogLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICAgICAqIEFkZGl0aW9uYWwgY29uZmlndXJhdGlvbiBmaWxlIHRvIGxvYWQuCiAgICAgKiAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgICogVGhpcyB2YXJpYWJsZS" in /ConfigFactory.php:48
    Stack trace:
     0. [throwable] Kraken\Throwable\Error\FatalError(...) in ErrorHandler:64
     1. [call] Kraken\Throwable\ErrorHandler::handleError(64, ""Kraken\Config\ConfigFactory::Kr...", "/opt/lampp/htdocs/kraken/test/kr...", 48) in ErrorHandler:80
     2. [call] Kraken\Throwable\ErrorHandler::handleShutdown(1) in EnvironmentProvider:45
     3. [call] Kraken\Root\Provider\EnvironmentProvider->Kraken\Root\Provider{closure}() in unknown:0
     4. [main]
Killed 

what can i do it?

**Comment by khelle** [comment]
You need to enable your `allow_url_include` setting in PHP.ini .

**Comment by michallkanak** [comment]
You have all, what you have to do - in first line of stacktrace - read! :) 

> wrapper is disabled in the server configuration by allow_url_include=0

**Comment by riky-cloud** [comment]
cool, :D
Server is booting...
Server is up!

thanks @khelle  and @michallkanak :+1: , it's my fault.. ;)
