### ISSUE TITLE
Kraken project:create throws an exception

### ISSUE THREAD

**Issue by abshammeri** [kraken-php/framework#45]
I executed the following:

as a root:

```
> composer create-project --prefer-dist kraken-php/kraken .
> php kraken.server
> php kraken server:ping 
> php kraken project:create
```

the last command throws this:

```
Executing : project:create ... failure!
Response  : "fwrite(): send of 159 bytes failed with errno=32 Broken pipe" in /home/vagrant/github/epp-client/vendor/kraken-php/util/Isolate/Isolate.php:73
Reason    : Kraken\Throwable\Error\NoticeError
```

PHP 5.6.17 (cli) (built: Jan  9 2016 10:31:18)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

Note that the following command works fine:

```
> php ./data/autorun/kraken.process undefined Main Main
```

Your help is appreciated. Thanks.

**Comment by khelle** [comment]
It seems like isolation mechanism did not spawn its subprocess. There is some things you can check / try :
- Are there any errors in logs? 
- If not, what is the reason that sub-processed returned with fail ?
- You could try to restore default `data` settings as something might be configured wrongly.
- Does the Kraken have proper chmod set for `data` directory ?

**Comment by tsdarky** [comment]
Restart kraken.server helped me

**Comment by khelle** [comment]
This problem occurs due the same reasons as #49 .
