### ISSUE TITLE
composer guzzle\* packages is abandoned 

### ISSUE THREAD

**Issue by hidehalo** [kraken-php/framework#58]
When I finished command "composer install", composer print those advices

```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle                                                                                      instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle                                                                                      instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle                                                                                      instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle i                                                                                     nstead.
```

Should we take the default advice?

**Comment by khelle** [comment]
This is used by one of kraken dependencies - Ratchet. Kraken does not use guzzle directly at all. For now it needs to stay until we get rid of it.

**Comment by pepijnblom** [comment]
@khelle Sorry for digging up this dead issue but it could be resolved I think. Ratchet 0.4 does not require those packages anymore. It was released 2017-09-14.

v0.4 requires

- php: >=5.4.2
- ratchet/rfc6455: ^0.2
- react/socket: ^1.0 || ^0.8 || ^0.7 || ^0.6 || ^0.5
- guzzlehttp/psr7: ^1.0
- symfony/http-foundation: ^2.2|^3.0
- symfony/routing: ^2.2|^3.0
